[package]
name = "aerospike-rt"
version = "2.0.0-alpha.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.9.0", features = ["fs", "net", "rt", "rt-multi-thread", "time", "io-util", "sync"], optional = true }
async-std = {version = "1.9.0", optional = true}

[features]
rt-tokio = ["tokio"]
rt-async-std = ["async-std"]
