#!/bin/bash

source $HOME/.cargo/env

git clone https://github.com/aerospike/aerospike-client-rust.git
cd aerospike-client-rust
git checkout v2
cargo clean
cargo fix --lib -p aerospike-core
cargo test

